/**
 * Connector abstraction — every accounting system (Yuki today, Exact / Twinfield
 * tomorrow) implements this interface. Routes never depend on a specific connector;
 * they ask the registry for `getConnectorForEntity(entityId)` and use the result.
 */

export interface ConnectorCredentials {
  /** Connector-specific opaque credential payload (already decrypted). */
  [key: string]: unknown;
}

export type ConnectorKind = "yuki" | "eboekhouden" | "mock" | "exact" | "twinfield";

export interface TrialBalanceLine {
  glAccountCode: string;
  glAccountName: string;
  /** "BALANCE" = balansrekening, "PROFIT_LOSS" = winst-en-verliesrekening */
  accountType: "BALANCE" | "PROFIT_LOSS";
  debit: number;
  credit: number;
  /** debit - credit (positive = debit balance, negative = credit balance) */
  balance: number;
  currency: string;
}

export interface TransactionLine {
  date: string; // ISO yyyy-MM-dd
  year: number;
  period: number;
  glAccountCode: string;
  glAccountName: string;
  accountType: "BALANCE" | "PROFIT_LOSS" | "UNKNOWN";
  amount: number; // signed; negative = credit
  contactName: string | null;
  /** Source document number (purchase/sales invoice number). Null for entries without a document. */
  reference: string | null;
  /** Source document kind, connector-native label (e.g. "Purchase invoice"). Null when unknown. */
  documentType: string | null;
  /** Project tag. Null when the connector/administration has no project on the line. */
  project: string | null;
  description: string;
  currency: string;

  /* ---- Provenance / VAT-mapping metadata (optional; set on synthesized lines) ---- */
  /** True when this line was generated by the connector (e.g. a VAT balancing
   *  line) rather than read 1:1 from a source posting. Raw source lines omit it. */
  generatedByConnector?: boolean;
  /** Source VAT code for a generated VAT line (e.g. "HOOG_VERK_21"). */
  vatCode?: string | null;
  /** Whether the GL account on a generated line came from explicit source data
   *  (the source API gave the VAT ledger). False when it had to be inferred. */
  sourceAccountKnown?: boolean;
  /** How the GL account on a generated line was resolved:
   *  - EXACT: taken from an explicit source account
   *  - INFERRED: resolved via ledger category (single unambiguous match)
   *  - REQUIRED: could not be resolved → needs a user-maintained VAT mapping */
  mappingConfidence?: "EXACT" | "INFERRED" | "REQUIRED";
}

export interface DateRange {
  from: string; // ISO yyyy-MM-dd
  to: string;   // ISO yyyy-MM-dd
}

export interface ContactSummary {
  id: string;
  name: string;
  code: string | null;
  isDebtor: boolean;
  isCreditor: boolean;
}

export interface ConnectionTestResult {
  ok: boolean;
  message: string;
  /** When ok=true: the administrations this credential can see. */
  administrations?: { id: string; name: string }[];
}

export interface Connector {
  readonly kind: ConnectorKind;

  testConnection(): Promise<ConnectionTestResult>;

  getTrialBalance(range: DateRange): Promise<TrialBalanceLine[]>;
  getTransactions(range: DateRange): Promise<TransactionLine[]>;

  getDebtors(): Promise<ContactSummary[]>;
  getCreditors(): Promise<ContactSummary[]>;
}
