/**
 * Connector abstraction — every accounting system (Yuki today, Exact / Twinfield
 * tomorrow) implements this interface. Routes never depend on a specific connector;
 * they ask the registry for `getConnectorForEntity(entityId)` and use the result.
 */

export interface ConnectorCredentials {
  /** Connector-specific opaque credential payload (already decrypted). */
  [key: string]: unknown;
}

export type ConnectorKind = "yuki" | "eboekhouden" | "mock" | "exact" | "twinfield";

export interface TrialBalanceLine {
  glAccountCode: string;
  glAccountName: string;
  /** "BALANCE" = balansrekening, "PROFIT_LOSS" = winst-en-verliesrekening */
  accountType: "BALANCE" | "PROFIT_LOSS";
  debit: number;
  credit: number;
  /** debit - credit (positive = debit balance, negative = credit balance) */
  balance: number;
  currency: string;

  /* ---- RGS normalization metadata (set by applyRgsMappings when enabled) ---- */
  rgsCode?: string | null;
  rgsType?: string | null;
  finCategory?: string | null;
}

export interface TransactionLine {
  date: string; // ISO yyyy-MM-dd
  year: number;
  period: number;
  glAccountCode: string;
  glAccountName: string;
  accountType: "BALANCE" | "PROFIT_LOSS" | "UNKNOWN";
  amount: number; // signed; negative = credit
  contactName: string | null;
  /** Source document number (purchase/sales invoice number). Null for entries without a document. */
  reference: string | null;
  /** Source document kind, connector-native label (e.g. "Purchase invoice"). Null when unknown. */
  documentType: string | null;
  /** Opaque ref to fetch this line's invoice PDF via getInvoicePdf(); null if none. */
  documentId?: string | null;
  /** Project tag. Null when the connector/administration has no project on the line. */
  project: string | null;
  description: string;
  currency: string;

  /* ---- Provenance / VAT-mapping metadata (optional; set on synthesized lines) ---- */
  /** True when this line was generated by the connector (e.g. a VAT balancing
   *  line) rather than read 1:1 from a source posting. Raw source lines omit it. */
  generatedByConnector?: boolean;
  /** Source VAT code for a generated VAT line (e.g. "HOOG_VERK_21"). */
  vatCode?: string | null;
  /** Whether the GL account on a generated line came from explicit source data
   *  (the source API gave the VAT ledger). False when it had to be inferred. */
  sourceAccountKnown?: boolean;
  /** How the GL account on a generated line was resolved:
   *  - EXACT: taken from an explicit source account
   *  - INFERRED: resolved via ledger category (single unambiguous match)
   *  - REQUIRED: could not be resolved → needs a user-maintained VAT mapping */
  mappingConfidence?: "EXACT" | "INFERRED" | "REQUIRED";

  /* ---- RGS normalization metadata (set by applyRgsMappings when enabled) ---- */
  /** Mapped RGS referentiecode for this line's source GL account, if any. */
  rgsCode?: string | null;
  /** RGS level/type of the mapped code ("account" | "mutation" | …). */
  rgsType?: string | null;
  /** FIN//HUB semantic category key (e.g. "MRR"), layered on top of RGS. */
  finCategory?: string | null;
}

export interface DateRange {
  from: string; // ISO yyyy-MM-dd
  to: string;   // ISO yyyy-MM-dd
}

export interface ContactSummary {
  id: string;
  name: string;
  code: string | null;
  isDebtor: boolean;
  isCreditor: boolean;
}

/** A single outstanding (open) invoice for receivables/payables + aging. */
export interface OutstandingItem {
  relationId: string;
  relationName: string;
  relationCode: string | null;
  invoiceNumber: string | null;
  /** Invoice date (ISO yyyy-MM-dd). */
  date: string;
  /** Due date (ISO) when the source provides it; aging falls back to `date`. */
  dueDate: string | null;
  totalAmount: number;
  /** Still-open amount. */
  openAmount: number;
  isDebtor: boolean;
  /** Opaque, connector-specific reference for fetching the invoice PDF via
   *  getInvoicePdf(). Null when no PDF is retrievable for this item. */
  documentId: string | null;
}

/** A retrieved invoice document (PDF). */
export interface InvoiceDocument {
  fileName: string;
  contentType: string;
  data: Buffer;
}

export interface ConnectionTestResult {
  ok: boolean;
  message: string;
  /** When ok=true: the administrations this credential can see. */
  administrations?: { id: string; name: string }[];
}

export interface Connector {
  readonly kind: ConnectorKind;

  testConnection(): Promise<ConnectionTestResult>;

  getTrialBalance(range: DateRange): Promise<TrialBalanceLine[]>;
  getTransactions(range: DateRange): Promise<TransactionLine[]>;

  getDebtors(): Promise<ContactSummary[]>;
  getCreditors(): Promise<ContactSummary[]>;

  /** Open invoices for receivables (debtor) or payables (creditor), with amounts. */
  getOutstanding(kind: "debtor" | "creditor"): Promise<OutstandingItem[]>;

  /** Fetch an invoice PDF by an OutstandingItem.documentId, or null if none. */
  getInvoicePdf(ref: string): Promise<InvoiceDocument | null>;
}
